# Ejemplos para acceder a archivos desde Kaggle o Google Drive

## Ejemplo de conexión a un Dataset de Kaggle

Normalmente en todos los dataset de Kaggle en la parte superior tienen un botón que dice `Code` ahí nos muestra como debemos conectarnos al dataset desde un programa en Python.

### Método 1

In [9]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [14]:
#df = pd.read_csv('/kaggle/input/datasets/abdulmalik1518/cars-datasets-2025/Cars Datasets 2025.csv',encoding='latin-1')

In [10]:
# Set the path to the file you'd like to load
file_path = "Cars Datasets 2025.csv"  # <-- Este nombre se puede visualizar en el lado derecho del sitio en Kaggle, se debe indicar el que se desea.

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "abdulmalik1518/cars-datasets-2025",
  file_path,
  pandas_kwargs={"encoding": "latin-1"},   # <-- Si el dataset está en una codificación diferente a UTF-8 debemos indicarlo
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_956/2261814197.py:5: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'cars-datasets-2025' dataset.
First 5 records:   Company Names     Cars Names      Engines CC/Battery Capacity HorsePower  \
0       FERRARI  SF90 STRADALE           V8             3990 cc     963 hp
1   ROLLS ROYCE        PHANTOM          V12             6749 cc     563 hp
2          Ford            KA+  1.2L Petrol            1,200 cc   70-85 hp
3      MERCEDES        GT 63 S           V8            3,982 cc     630 hp
4          AUDI     AUDI R8 Gt          V10            5,204 cc     602 hp

  Total Speed Performance(0 - 100 )KM/H      Cars Prices       Fuel Types  \
0    340 km/h                   2.5 sec      $1,100,000   plug in hyrbrid
1    250 km/h                   5.3 sec        $460,000            Petrol
2    165 km/h                  10.5 sec  $12,000-$15,000           Petrol
3    250 km/h                   3.2 sec        $161,000            Petrol
4    320 km/h                   3.6 sec        $253,290            Petrol

  Seats        Torque
0     2        800 Nm
1     5        900 Nm
2     5  100 - 140 Nm
3     4        900 Nm
4     2        560 Nm

In [11]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

### Método 2


Para este método se debe crear un API_TOKEN en la configuración de la cuenta de Kaggle. Posteriormente agregarlo en Colab usando el botón de `Secretos` de la barra de la izquierda (es una llave).

In [15]:
import os
from google.colab import userdata
import kagglehub

# 1. Recuperamos el token guardado de forma segura en Colab
os.environ["KAGGLE_API_TOKEN"] = userdata.get('KAGGLE_API_TOKEN')

# 2. Descargamos el dataset usando la nueva herramienta kagglehub
# Reemplaza con el usuario/nombre-del-dataset que busques
path = kagglehub.dataset_download("abdulmalik1518/cars-datasets-2025")

print("El dataset se descargó correctamente en la ruta:", path)

Using Colab cache for faster access to the 'cars-datasets-2025' dataset.
El dataset se descargó correctamente en la ruta: /kaggle/input/cars-datasets-2025

In [16]:
!ls /kaggle/input/cars-datasets-2025

'Cars Datasets 2025.csv'

In [18]:
import pandas as pd
df = pd.read_csv('/kaggle/input/cars-datasets-2025/Cars Datasets 2025.csv',encoding='latin-1')
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

## Ejemplo de descarga de archivo desde Google Drive

In [ ]:
# Instalamos la biblioteca gdown

!pip install gdown

Para descargar el archivo desde Google Drive, se debe haber compartido con derechos de [Lector] y vanos a utilizar el código del archivo el cual podemso extraer del vínculo de compartición.

Ejemplo:

https://drive.google.com/file/d/1YrTSVK2NyYAVGn1rOLz8HQlsvFEY8oqD/view?usp=sharing

En el vínculo anterior el código está entre las secciones `https://drive.google.com/file/d/` y `/view?usp=sharing`

In [ ]:
import gdown
#En el parámetro output le indicamos el nombre del archivo con el que se guardará.
gdown.download(id='1YrTSVK2NyYAVGn1rOLz8HQlsvFEY8oqD', output='nombre_archivo.csv', quiet=False)